### ISSUE TITLE
`config.settings` regression

### ISSUE THREAD

**Issue by parndt** [dry-rb/dry-configurable#80]
**Describe the bug**

When using `setting :settings, reader: true` I was previously able to access
the setting with:
```ruby
config.settings.my_setting_name
```
Now it's:
```ruby
config.settings[:settings].value.my_setting_name
```

**To Reproduce**

More information on Zulip: https://dry-rb.zulipchat.com/#narrow/stream/191662-general/topic/dry-system/near/188358017

**Expected behavior**

The previous behaviour.

**Your environment**

- Affects my production application: Not yet. It would if it passed CI!
- Ruby version: 2.6.5
- OS: macOS

**Comment by parndt** [comment]
Here you go @solnic

**Comment by flash-gordon** [comment]
IIRC it's not the first time this happens, I saw something similar when I was rewriting dry-configurable _the previous time_, yet we still don't have a spec somehow. Maybe it was a different key though

**Comment by solnic** [comment]
@flash-gordon this can be easily fixed *and* improved - we need to generate a list of reserved key words based on `Config` public methods and raise a meaningful exception when somebody tries to access a reserved key word, saying "you #[]` instead. When it comes to methods that the library implements itself, we just need to prefix them with `_` so that we at least reduce the number of reserved key words.

**Comment by parndt** [comment]
Thanks! :+1:
